### ISSUE TITLE
undefined constant File::DEVNULL

### ISSUE THREAD

**Issue by RemiKalbe** [onyxframework/http#82]
I just created a project to switch from Kemal to Onyx and when I wanted to start the server I got this error:

```bash
Error in lib/onyx/src/onyx/logger.cr:21: undefined constant File::DEVNULL

    ENV["CRYSTAL_ENV"] == "benchmarking" ? File.open(File::DEVNULL, "w") : STDOUT,
```
My shard.lock
```yaml
version: 1.0
shards:
  ameba:
    github: veelenga/ameba
    version: 0.10.0

  callbacks:
    github: vladfaust/callbacks.cr
    version: 0.2.0

  crest:
    github: mamantoha/crest
    version: 0.20.0

  dotenv:
    github: gdotdesign/cr-dotenv
    version: 0.1.0

  exception_page:
    github: crystal-loot/exception_page
    version: 0.1.2

  http-params-serializable:
    github: vladfaust/http-params-serializable
    version: 0.3.0

  kilt:
    github: jeromegn/kilt
    version: 0.4.0

  onyx:
    github: onyxframework/onyx
    version: 0.4.3

  onyx-http:
    github: onyxframework/http
    version: 0.8.2

  radix:
    github: luislavena/radix
    version: 0.3.9

  time_format:
    github: vladfaust/time_format.cr
    version: 0.1.1

```

My Crystal version
```
Crystal 0.29.0 (2019-06-06)

LLVM: 6.0.1
Default target: x86_64-apple-macosx
```
